package iaw.pc.runtime;

import iaw.pc.messages.PhoneCall;
import iaw.pc.messages.SMS;

import org.springframework.integration.annotation.Transformer;
import org.springframework.mail.MailMessage;
import org.springframework.mail.SimpleMailMessage;


public class SMSTransformer {

	@Transformer
	public SMS transform(PhoneCall call){
		SMS sms = new SMS();
		sms.setFrom("PCMS Unijui");
		
		String body="This is an automatic sms generated by the Phone Call Management System\n";
		body += "Call to " + call.getDestination() + " was succesfully charged in your account.\n";
		body += "Details:\n";
		body += "\tDuration: "+ call.getDestination().getDuration()+"\n";
		body += "\tCost: " + call.getDestination().getCost()+"\n";
		
		sms.setBody(body);
		
		return sms;
	}
}
